/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RecoverRouteImport } from './routes/recover'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MessengerRouteImport } from './routes/messenger'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as HelpRouteImport } from './routes/help'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as CommunitiesRouteImport } from './routes/communities'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as AdsRouteImport } from './routes/ads'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIdRouteImport } from './routes/user.$id'
import { Route as CommunitiesIdRouteImport } from './routes/communities.$id'
import { Route as CategoriesIdRouteImport } from './routes/categories.$id'
import { Route as AdsNewRouteImport } from './routes/ads.new'
import { Route as AdsIdRouteImport } from './routes/ads.$id'
import { Route as CategoriesIdSubIdRouteImport } from './routes/categories.$id.$subId'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverRoute = RecoverRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MessengerRoute = MessengerRouteImport.update({
  id: '/messenger',
  path: '/messenger',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesRoute = CommunitiesRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsRoute = AdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdRoute = UserIdRouteImport.update({
  id: '/user/$id',
  path: '/user/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesIdRoute = CommunitiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CommunitiesRoute,
} as any)
const CategoriesIdRoute = CategoriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CategoriesRoute,
} as any)
const AdsNewRoute = AdsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdsRoute,
} as any)
const AdsIdRoute = AdsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdsRoute,
} as any)
const CategoriesIdSubIdRoute = CategoriesIdSubIdRouteImport.update({
  id: '/$subId',
  path: '/$subId',
  getParentRoute: () => CategoriesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ads': typeof AdsRouteWithChildren
  '/categories': typeof CategoriesRouteWithChildren
  '/communities': typeof CommunitiesRouteWithChildren
  '/friends': typeof FriendsRoute
  '/help': typeof HelpRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/messenger': typeof MessengerRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/recover': typeof RecoverRoute
  '/register': typeof RegisterRoute
  '/subscription': typeof SubscriptionRoute
  '/welcome': typeof WelcomeRoute
  '/ads/$id': typeof AdsIdRoute
  '/ads/new': typeof AdsNewRoute
  '/categories/$id': typeof CategoriesIdRouteWithChildren
  '/communities/$id': typeof CommunitiesIdRoute
  '/user/$id': typeof UserIdRoute
  '/categories/$id/$subId': typeof CategoriesIdSubIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ads': typeof AdsRouteWithChildren
  '/categories': typeof CategoriesRouteWithChildren
  '/communities': typeof CommunitiesRouteWithChildren
  '/friends': typeof FriendsRoute
  '/help': typeof HelpRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/messenger': typeof MessengerRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/recover': typeof RecoverRoute
  '/register': typeof RegisterRoute
  '/subscription': typeof SubscriptionRoute
  '/welcome': typeof WelcomeRoute
  '/ads/$id': typeof AdsIdRoute
  '/ads/new': typeof AdsNewRoute
  '/categories/$id': typeof CategoriesIdRouteWithChildren
  '/communities/$id': typeof CommunitiesIdRoute
  '/user/$id': typeof UserIdRoute
  '/categories/$id/$subId': typeof CategoriesIdSubIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ads': typeof AdsRouteWithChildren
  '/categories': typeof CategoriesRouteWithChildren
  '/communities': typeof CommunitiesRouteWithChildren
  '/friends': typeof FriendsRoute
  '/help': typeof HelpRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/messenger': typeof MessengerRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/recover': typeof RecoverRoute
  '/register': typeof RegisterRoute
  '/subscription': typeof SubscriptionRoute
  '/welcome': typeof WelcomeRoute
  '/ads/$id': typeof AdsIdRoute
  '/ads/new': typeof AdsNewRoute
  '/categories/$id': typeof CategoriesIdRouteWithChildren
  '/communities/$id': typeof CommunitiesIdRoute
  '/user/$id': typeof UserIdRoute
  '/categories/$id/$subId': typeof CategoriesIdSubIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ads'
    | '/categories'
    | '/communities'
    | '/friends'
    | '/help'
    | '/landing'
    | '/login'
    | '/messenger'
    | '/onboarding'
    | '/profile'
    | '/recover'
    | '/register'
    | '/subscription'
    | '/welcome'
    | '/ads/$id'
    | '/ads/new'
    | '/categories/$id'
    | '/communities/$id'
    | '/user/$id'
    | '/categories/$id/$subId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ads'
    | '/categories'
    | '/communities'
    | '/friends'
    | '/help'
    | '/landing'
    | '/login'
    | '/messenger'
    | '/onboarding'
    | '/profile'
    | '/recover'
    | '/register'
    | '/subscription'
    | '/welcome'
    | '/ads/$id'
    | '/ads/new'
    | '/categories/$id'
    | '/communities/$id'
    | '/user/$id'
    | '/categories/$id/$subId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ads'
    | '/categories'
    | '/communities'
    | '/friends'
    | '/help'
    | '/landing'
    | '/login'
    | '/messenger'
    | '/onboarding'
    | '/profile'
    | '/recover'
    | '/register'
    | '/subscription'
    | '/welcome'
    | '/ads/$id'
    | '/ads/new'
    | '/categories/$id'
    | '/communities/$id'
    | '/user/$id'
    | '/categories/$id/$subId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdsRoute: typeof AdsRouteWithChildren
  CategoriesRoute: typeof CategoriesRouteWithChildren
  CommunitiesRoute: typeof CommunitiesRouteWithChildren
  FriendsRoute: typeof FriendsRoute
  HelpRoute: typeof HelpRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  MessengerRoute: typeof MessengerRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  RecoverRoute: typeof RecoverRoute
  RegisterRoute: typeof RegisterRoute
  SubscriptionRoute: typeof SubscriptionRoute
  WelcomeRoute: typeof WelcomeRoute
  UserIdRoute: typeof UserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover': {
      id: '/recover'
      path: '/recover'
      fullPath: '/recover'
      preLoaderRoute: typeof RecoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messenger': {
      id: '/messenger'
      path: '/messenger'
      fullPath: '/messenger'
      preLoaderRoute: typeof MessengerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities': {
      id: '/communities'
      path: '/communities'
      fullPath: '/communities'
      preLoaderRoute: typeof CommunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads': {
      id: '/ads'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof AdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$id': {
      id: '/user/$id'
      path: '/user/$id'
      fullPath: '/user/$id'
      preLoaderRoute: typeof UserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/$id': {
      id: '/communities/$id'
      path: '/$id'
      fullPath: '/communities/$id'
      preLoaderRoute: typeof CommunitiesIdRouteImport
      parentRoute: typeof CommunitiesRoute
    }
    '/categories/$id': {
      id: '/categories/$id'
      path: '/$id'
      fullPath: '/categories/$id'
      preLoaderRoute: typeof CategoriesIdRouteImport
      parentRoute: typeof CategoriesRoute
    }
    '/ads/new': {
      id: '/ads/new'
      path: '/new'
      fullPath: '/ads/new'
      preLoaderRoute: typeof AdsNewRouteImport
      parentRoute: typeof AdsRoute
    }
    '/ads/$id': {
      id: '/ads/$id'
      path: '/$id'
      fullPath: '/ads/$id'
      preLoaderRoute: typeof AdsIdRouteImport
      parentRoute: typeof AdsRoute
    }
    '/categories/$id/$subId': {
      id: '/categories/$id/$subId'
      path: '/$subId'
      fullPath: '/categories/$id/$subId'
      preLoaderRoute: typeof CategoriesIdSubIdRouteImport
      parentRoute: typeof CategoriesIdRoute
    }
  }
}

interface AdsRouteChildren {
  AdsIdRoute: typeof AdsIdRoute
  AdsNewRoute: typeof AdsNewRoute
}

const AdsRouteChildren: AdsRouteChildren = {
  AdsIdRoute: AdsIdRoute,
  AdsNewRoute: AdsNewRoute,
}

const AdsRouteWithChildren = AdsRoute._addFileChildren(AdsRouteChildren)

interface CategoriesIdRouteChildren {
  CategoriesIdSubIdRoute: typeof CategoriesIdSubIdRoute
}

const CategoriesIdRouteChildren: CategoriesIdRouteChildren = {
  CategoriesIdSubIdRoute: CategoriesIdSubIdRoute,
}

const CategoriesIdRouteWithChildren = CategoriesIdRoute._addFileChildren(
  CategoriesIdRouteChildren,
)

interface CategoriesRouteChildren {
  CategoriesIdRoute: typeof CategoriesIdRouteWithChildren
}

const CategoriesRouteChildren: CategoriesRouteChildren = {
  CategoriesIdRoute: CategoriesIdRouteWithChildren,
}

const CategoriesRouteWithChildren = CategoriesRoute._addFileChildren(
  CategoriesRouteChildren,
)

interface CommunitiesRouteChildren {
  CommunitiesIdRoute: typeof CommunitiesIdRoute
}

const CommunitiesRouteChildren: CommunitiesRouteChildren = {
  CommunitiesIdRoute: CommunitiesIdRoute,
}

const CommunitiesRouteWithChildren = CommunitiesRoute._addFileChildren(
  CommunitiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdsRoute: AdsRouteWithChildren,
  CategoriesRoute: CategoriesRouteWithChildren,
  CommunitiesRoute: CommunitiesRouteWithChildren,
  FriendsRoute: FriendsRoute,
  HelpRoute: HelpRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  MessengerRoute: MessengerRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  RecoverRoute: RecoverRoute,
  RegisterRoute: RegisterRoute,
  SubscriptionRoute: SubscriptionRoute,
  WelcomeRoute: WelcomeRoute,
  UserIdRoute: UserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
